// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwwphvlzwjlzcdnkninw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3d3Bodmx6d2psemNkbmtuaW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTQ4NDksImV4cCI6MjA2NTQ3MDg0OX0.10VKsdxekPE9hWp01hBhkz1Xf6GdzfLVWGA_u7e04bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);